layers:

  input:
    size: 2
    activation_function: linear
    bias_node: true
  
  hidden:
    size: 2
    activation_function: logistic
    bias_node: true
  
  output:
    size: 1
    activation_function: linear


links:

  input_hidden: 
    pre: input
    post: hidden
    plastic: false
    connection_type: full
    display: true
    learning_rate: 0.2
    weights:
      - 0.3
      - 0.7
    
  hidden_output:
    pre: hidden
    post: output
    plastic: false
    connection_type: full
    learning_rate: 0.2
    display: true
    weights:
      - 0.3
      - 0.7


order:
  - input
  - hidden
  - output
